apiVersion: batch/v1
kind: Job
metadata:
  name: service-uno
spec:
  template:
    metadata:
      name: service-uno-pod
    spec:
      containers:
      - name: service-uno-container
        image: service-uno:1.0.0
        imagePullPolicy: Never
      restartPolicy: Never